spring.application.name=limio-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:limio}
spring.datasource.username=${DB_USERNAME:limio}
spring.datasource.password=${DB_PASSWORD:limio}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
